GET http://localhost:4004/catalog/Books

###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{
    "ID": 11, 
    "title": "Another book", 
    "stock": 10
}

###
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{
    "book_ID": 421,
    "quantity": 10
}