GET http://localhost:4004/catalog/Authors?$expand=books

###
GET http://localhost:4004/catalog/Books?$expand=author

###
POST http://localhost:4004/catalog/Authors
Content-Type: application/json

{
    "ID": 4711,
    "name": "Renan Ciciliato"
}

###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{
    "ID": 999,
    "title": "The book is on the table",
    "stock": 10,
    "author_ID": 4711
}